controller:
  # admin config should be setted in ./secrets.yaml file, for example:
  # admin:
  #   username: admin
  #   password: password

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - job-dsl:latest

  JCasC:
    configScripts:
      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default.svc"
                namespace: "jenkins"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:80"
                jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
                templates:
                  - name: "kaniko-agent"
                    namespace: "jenkins"
                    serviceAccount: "jenkins"
                    containers:
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:debug"
                        command: "/busybox/cat"
                        ttyEnabled: true
                        resourceRequestCpu: "500m"
                        resourceRequestMemory: "1Gi"
                        resourceLimitCpu: "1"
                        resourceLimitMemory: "2Gi"
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:latest"
                        resourceRequestCpu: "200m"
                        resourceRequestMemory: "256Mi"
      pipeline-job: |
        jobs:
          - script: >
              pipelineJob('django-app') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/Costbound/goit-devops.git')
                          credentials('github-credentials')
                        }
                        branch('*/lesson-8-9')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }
