{{- if .Values.repository.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .Values.repository.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.repository.url }}
  username: {{ .Values.repository.username }}
  password: {{ .Values.repository.password }}
{{- end }}
